//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterLayoutEx.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_login
    {
        
        [Required(ErrorMessage = "Username is Required")]
        public string username { get; set; }
        [Required(ErrorMessage = "Password is Required")]
        public string password { get; set; }
        public string usertype { get; set; }
        
    }
    
}
